### ISSUE TITLE
Playback stutters

### ISSUE THREAD

**Issue by RyanTheNerd** [LenShustek/miditones#13]
I have this midi file that when converted doesn't play properly. It seems to stutter quite a bit.
I'm using an arduboy which is based on the arduino Leonardo with miditones V1.16
[c file and source midi](https://drive.google.com/open?id=1NLlLE0aqMY_NSSR5BB6zUIMe9J1PssCW)

**Comment by LenShustek** [comment]
Ryan,
I tried on on an Arduino Uno, which is the closest thing to a Leonardo I have, using the 15 Aug 2016 version of Playtune, and it seems to work ok.  Listen to the attached audio file. 
Are you executing some code while the song is playing that might be interfering with the interrupt timing?
Len
[mario_II.zip](https://github.com/LenShustek/miditones/files/1849259/mario_II.zip)

**Comment by RyanTheNerd** [comment]
The code I'm trying it with has nothing in the loop, so nothing should be interfering with it. It stutters on both the arduboy library by itself and the arduboy2 library with ArduboyPlaytune.

**Comment by LenShustek** [comment]
Well, I took a look at ArduboyPlaytune for the first time, and it's pretty much different code that is "inspired by" Playtune, so it's hard for me to debug it, especially without an ardoboy.

But being based on an earlier version of Playtune, it looks like it doesn't have a bug fix that I did in August of 2016 that had to do with incorrect score timing: 

>     - Fixed a timing error: T Wasiluk's change to using a 16-bit timer instead
        of an 8-bit timer for score waits exposed a old bug that was in the original
        Brett Hagman code: when writing the timer OCR value, we need to clear the
        timer counter, or else (the manual says) "the counter [might] miss the compare
        match...and will have to count to its maximum value (0xFFFF) and wrap around
        starting at 0 before the compare match can occur". This caused an error that
        was small and not noticeable for the 8-bit timer, but could be hundreds of
        milliseconds for the 16-bit counter. Thanks go to Joey Babcock for pushing me
        to figure out why his music sounded weird, and for discovering that it worked
        ok with the 2013 version that used the 8-bit timer for score waits.

If you want to see if that helps, after "OCR1A = ocr;" do "TCNT1 = 0;", and after "OCR3A = ocr;" do "TCNT3 = 0;"

**Comment by RyanTheNerd** [comment]
That was it, thanks! It runs perfectly now.

**Comment by MLXXXp** [comment]
This fix has now been merged into [ArduboyPlaytune](https://github.com/Arduboy/ArduboyPlaytune) and released as version 1.0.4
