### ISSUE TITLE
Initial notes without delay

### ISSUE THREAD

**Issue by qistoph** [LenShustek/miditones#15]
The miditones file I get generated starts with a couple of notes all in the same track before any wait. I think this is wrong, because I assume these will be played really, really fast until the first actual delay plays the last note in this sequence.

```
00000000  90 30 91 40 90 30 91 40  90 30 91 40 90 30 91 40  |.0.@.0.@.0.@.0.@|
00000010  90 30 91 40 90 30 91 40  90 30 91 40 90 2b 91 3b  |.0.@.0.@.0.@.+.;|
00000020  90 2b 91 3b 90 32 91 42  90 32 91 42 00 9f 80 81  |.+.;.2.B.2.B....|
00000030  00 01 90 32 91 42 01 e2  80 81 00 01 90 32 91 42  |...2.B.......2.B|
...
```

This is the miditones_scroll output:
```
duration    time    gen0  gen1  gen2  gen3  gen4  gen5         bytestream code

  159       0.000    3D    4F#                           0000: 90 30 91 40 90 30 91 40 90 30 91 40 90 30 91 40 90 30 91 40 90 30 91 40 90 30 91 40 90 2B 91 3B 90 2B 91 3B 90 32 91 42 90 32 91 42 00 9F 
    1       0.159                                        002E: 80 81 00 01 
  482       0.160    3D    4F#                           0032: 90 32 91 42 01 E2 
    1       0.642                                        0038: 80 81 00 01 
  482       0.643    3D    4F#                           003C: 90 32 91 42 01 E2 
...
```

Is my assumption correct? Do you need any additional information?

**Comment by LenShustek** [comment]
Yes, that looks strange. Can you send me the MIDI file it was generated from?

**Comment by LenShustek** [comment]
Ok, thanks. It definitely looks like my bug; some delays are not being generated when they should. I'll be able to look at it in detail, and hopefully fix it, on Wednesday.

**Comment by qistoph** [comment]
Thanks, don't feel rushed. I'm reporting it mainly to prevent other less noticeable errors. I don't think I'm hearing anything weird in this case.

**Comment by LenShustek** [comment]
It was a simple bug: delays weren't being generated until the tempo was set, which didn't happen in your MIDI file until almost four seconds into the song. I hadn't seen that before, and I was using 0 as the default tempo instead of the correct value (according to the MIDI spec) of 500,000 usec/beat.

I just uploaded the fixed source code and Windows executable. Let me know if that works for you. And thanks for reporting the problem.

**Comment by qistoph** [comment]
Looks good to me! Thanks for you quick fix.
