### ISSUE TITLE
.exe can not be run

### ISSUE THREAD

**Issue by GhostJumper** [LenShustek/miditones#20]
exe can not be run.

- ucrtbased.dll seems to be missing
- VCRUNTIME140D.dll seems to be missing

System:
- Windows 10 Pro x64 (Version 1809) (OS-Build 17763.503)

Installed "Microsoft Visual C++" Versions:
- Microsoft Visual C++ 2017 Redistributable (x86) - 14.15.27027
- Microsoft Visual C++ 2017 Redistributable (x64) - 14.15.26706
- Microsoft Visual C++ 2013 Redistributable (x86) - 12.0.40660
- Microsoft Visual C++ 2013 Redistributable (x86) - 12.0.30501
- Microsoft Visual C++ 2013 Redistributable (x64) - 12.0.40660
- Microsoft Visual C++ 2013 Redistributable (x64) - 12.0.30501
- Microsoft Visual C++ 2012 Redistributable (x64) - 11.0.61030
- Microsoft Visual C++ 2012 Redistributable (x86) - 11.0.61030
- Microsoft Visual C++ 2010 x64 Redistributable - 10.0.40219
- Microsoft Visual C++ 2010 x86 Redistributable - 10.0.40219
- Microsoft Visual C++ 2008 Redistributable - x64 9.0.30729.17
- Microsoft Visual C++ 2008 Redistributable - x86 9.0.21022
- Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729.17
- Microsoft Visual C++ 2005 Redistributable (x64)
- Microsoft Visual C++ 2005 Redistributable

**Comment by LenShustek** [comment]
Apparently that's a common problem with Visual Studio executables:
https://social.msdn.microsoft.com/Forums/windows/en-US/06b66cae-d010-441d-bc72-64a8c7cd65bc/missing-vcruntime140ddll-and-ucrtbaseddll
https://developercommunity.visualstudio.com/content/problem/25662/console-c-application-compiled-in-vs-2017-fails-to.html

But I might have uploaded a version compiled with debugging, which contributes to the problem. I just uploaded a version compiled for "release"; see if that works better.

**Comment by GhostJumper** [comment]
Thank you. The .exe is now running as it should.
