### ISSUE TITLE
"access is denied" in win 10.

### ISSUE THREAD

**Issue by salukikev** [LenShustek/miditones#21]
I've tried to run this on 3 different systems (an old 32bit winXp, a newer winXp, and my usual Win10x64)- using the simple command line executable to simplify/covert a mid file to code.  

In win10, my error is a simple ambiguous "Access is denied".  

I'm running my CMD as administrator.
I've tried changing permissions to the folder.
I may uninstall Comodo firewall- but I don't think that's it.
I can't tell if I'm doing something wrong, or if there is a problem with the file, or my OS.

Win10 x64 Pro (version 1903 OS build 18362.239)
Microsoft Visual C++ 2015-2019 Redistributable (x64) - 14.22.27821
Thanks for any help!  This will be fantastic if I can get it to work!

**Comment by LenShustek** [comment]
Ok, lelt's gets some evidence to try to figure out what's going on. Copy the latest minitones.exe executable dated May 28 to a user (not system) directory. Open a command window there, and just type "miditones". If you get the program instructions, then the problem must be accessing data files. If you get "Access is denied", then there is a Windows permission problem running the program itself. (There's nothing about miditones that should need administrator privileges.)

**Comment by salukikev** [comment]
Hey- thanks for the super quick reply!  I thought the earlier folder may have been a system one but changed the settings for it, then also retried it with a folder in my documents & my desktop.  All same result of "access denied".  Still- I guess this illustrates that I'm not configuring it correctly or else there is something going on with my system(s).  Still, I'm somewhat new to github and I wonder if I need other supplemental files/applications configured in order to make this work that are probably obvious to everyone else.  This is a simple executable, correct? Just like the old DOS days..?  We can close this issue if you like as I think we've concluded the problem(s) aren't with the files you posted.  Thanks again!

**Comment by LenShustek** [comment]
I did a quick test by copying miditones.exe from the GitHub repository to a new empty subdirectory of C:\ on my wife's computer (which has none of the program development tools), and it executed fine. So there must be something not right with the permission settings on your computer.
