### ISSUE TITLE
can't get more than three pins to function at a time

### ISSUE THREAD

**Issue by craftingiskoolya** [LenShustek/miditones#3]
Hello,
I am unable to make more than three pins on my arduino uno output tones to the speaker. Last I checked, the chip on the uno does have 6 timers built in. Is there any way to fix this?

**Comment by LenShustek** [comment]
The Arduino Uno uses the ATmega328 processor, which only has 3 timers (two 8-bit and one 16-bit). So it can only play 3 channels with the PlayTune software. Sorry about that.

The Arduino Mega uses the ATmega2560 processor, which has 6 timers (two 8-bit and four 16-bit), and it will play six channels with PlayTune.
