### ISSUE TITLE
Can't seem to run it with Mac OS X

### ISSUE THREAD

**Issue by Spaceddd** [LenShustek/miditones#8]
Hi, I'm trying to use it with Mac OS X. I downloaded the source code and compiled miditones.c, thinking that in doing so I would be able to use the commands, it does compile perfectly but when I try to use a command it doesn't seem to recognize it. Then I tried to compile the miditones_scroll and that gives me a bunch of errors, I can't seem to find a way to make this work on Mac, maybe I'm doing something wrong? I'm no guru.
I'm using El Capitan, OS 10.11.6

Here's the list of errors it gave me:

miditones_scroll.c:155:8: error: expected parameter declarator

size_t strlcpy(char *dst, const char *src, size_t       siz) {
       ^
/usr/include/secure/_string.h:105:44: note: expanded from macro 'strlcpy'
  __builtin___strlcpy_chk (dest, src, len, __darwin_obsz (dest))
                                           ^
/usr/include/secure/_common.h:39:62: note: expanded from macro '__darwin_obsz'
#define __darwin_obsz(object) __builtin_object_size (object, _USE_FORTIF...
                                                             ^
/usr/include/secure/_common.h:30:32: note: expanded from macro
      '_USE_FORTIFY_LEVEL'
#    define _USE_FORTIFY_LEVEL 2
                               ^
miditones_scroll.c:155:8: error: expected ')'
/usr/include/secure/_string.h:105:44: note: expanded from macro 'strlcpy'
  __builtin___strlcpy_chk (dest, src, len, __darwin_obsz (dest))
                                           ^
/usr/include/secure/_common.h:39:62: note: expanded from macro '__darwin_obsz'
#define __darwin_obsz(object) __builtin_object_size (object, _USE_FORTIF...
                                                             ^
/usr/include/secure/_common.h:30:32: note: expanded from macro
      '_USE_FORTIFY_LEVEL'
#    define _USE_FORTIFY_LEVEL 2
                               ^
miditones_scroll.c:155:8: note: to match this '('
/usr/include/secure/_string.h:105:44: note: expanded from macro 'strlcpy'
  __builtin___strlcpy_chk (dest, src, len, __darwin_obsz (dest))
                                           ^
/usr/include/secure/_common.h:39:53: note: expanded from macro '__darwin_obsz'
#define __darwin_obsz(object) __builtin_object_size (object, _USE_FORTIF...
                                                    ^
miditones_scroll.c:155:8: warning: type specifier missing, defaults to 'int'
      [-Wimplicit-int]
size_t strlcpy(char *dst, const char *src, size_t       siz) {
       ^
/usr/include/secure/_string.h:105:44: note: expanded from macro 'strlcpy'
  __builtin___strlcpy_chk (dest, src, len, __darwin_obsz (dest))
                                           ^
/usr/include/secure/_common.h:39:31: note: expanded from macro '__darwin_obsz'
#define __darwin_obsz(object) __builtin_object_size (object, _USE_FORTIF...
                              ^
miditones_scroll.c:155:8: error: conflicting types for '__builtin___strlcpy_chk'
/usr/include/secure/_string.h:105:3: note: expanded from macro 'strlcpy'
  __builtin___strlcpy_chk (dest, src, len, __darwin_obsz (dest))
  ^
miditones_scroll.c:155:8: note: '__builtin___strlcpy_chk' is a builtin with type
      'unsigned long (char *, const char *, unsigned long, unsigned long)'
/usr/include/secure/_string.h:105:3: note: expanded from macro 'strlcpy'
  __builtin___strlcpy_chk (dest, src, len, __darwin_obsz (dest))
  ^
miditones_scroll.c:155:8: error: definition of builtin function
      '__builtin___strlcpy_chk'
size_t strlcpy(char *dst, const char *src, size_t       siz) {
       ^
/usr/include/secure/_string.h:105:3: note: expanded from macro 'strlcpy'
  __builtin___strlcpy_chk (dest, src, len, __darwin_obsz (dest))
  ^
miditones_scroll.c:181:8: error: expected parameter declarator
size_t strlcat(char *dst, const char *src, size_t siz) {
       ^
/usr/include/secure/_string.h:111:44: note: expanded from macro 'strlcat'
  __builtin___strlcat_chk (dest, src, len, __darwin_obsz (dest))
                                           ^
/usr/include/secure/_common.h:39:62: note: expanded from macro '__darwin_obsz'
#define __darwin_obsz(object) __builtin_object_size (object, _USE_FORTIF...
                                                             ^
/usr/include/secure/_common.h:30:32: note: expanded from macro
      '_USE_FORTIFY_LEVEL'
#    define _USE_FORTIFY_LEVEL 2
                               ^
miditones_scroll.c:181:8: error: expected ')'
/usr/include/secure/_string.h:111:44: note: expanded from macro 'strlcat'
  __builtin___strlcat_chk (dest, src, len, __darwin_obsz (dest))
                                           ^
/usr/include/secure/_common.h:39:62: note: expanded from macro '__darwin_obsz'
#define __darwin_obsz(object) __builtin_object_size (object, _USE_FORTIF...
                                                             ^
/usr/include/secure/_common.h:30:32: note: expanded from macro
      '_USE_FORTIFY_LEVEL'
#    define _USE_FORTIFY_LEVEL 2
                               ^
miditones_scroll.c:181:8: note: to match this '('
/usr/include/secure/_string.h:111:44: note: expanded from macro 'strlcat'
  __builtin___strlcat_chk (dest, src, len, __darwin_obsz (dest))
                                           ^
/usr/include/secure/_common.h:39:53: note: expanded from macro '__darwin_obsz'
#define __darwin_obsz(object) __builtin_object_size (object, _USE_FORTIF...
                                                    ^
miditones_scroll.c:181:8: warning: type specifier missing, defaults to 'int'
      [-Wimplicit-int]
size_t strlcat(char *dst, const char *src, size_t siz) {
       ^
/usr/include/secure/_string.h:111:44: note: expanded from macro 'strlcat'
  __builtin___strlcat_chk (dest, src, len, __darwin_obsz (dest))
                                           ^
/usr/include/secure/_common.h:39:31: note: expanded from macro '__darwin_obsz'
#define __darwin_obsz(object) __builtin_object_size (object, _USE_FORTIF...
                              ^
miditones_scroll.c:181:8: error: conflicting types for '__builtin___strlcat_chk'
/usr/include/secure/_string.h:111:3: note: expanded from macro 'strlcat'
  __builtin___strlcat_chk (dest, src, len, __darwin_obsz (dest))
  ^
miditones_scroll.c:181:8: note: '__builtin___strlcat_chk' is a builtin with type
      'unsigned long (char *, const char *, unsigned long, unsigned long)'
/usr/include/secure/_string.h:111:3: note: expanded from macro 'strlcat'
  __builtin___strlcat_chk (dest, src, len, __darwin_obsz (dest))
  ^
miditones_scroll.c:181:8: error: definition of builtin function
      '__builtin___strlcat_chk'
size_t strlcat(char *dst, const char *src, size_t siz) {
       ^
/usr/include/secure/_string.h:111:3: note: expanded from macro 'strlcat'
  __builtin___strlcat_chk (dest, src, len, __darwin_obsz (dest))
  ^
miditones_scroll.c:211:77: warning: format specifies type 'unsigned int' but the
      argument has type 'long' [-Wformat]
  ...file format error at position %04X (%d): %s\n", bufptr-buffer, bufptr-bu...
                                   ~~~~              ^~~~~~~~~~~~~
                                   %04lX
miditones_scroll.c:211:92: warning: format specifies type 'int' but the argument
      has type 'long' [-Wformat]
  ...error at position %04X (%d): %s\n", bufptr-buffer, bufptr-buffer, msg);
                             ~~                         ^~~~~~~~~~~~~
                             %ld
miditones_scroll.c:227:47: warning: format specifies type 'int' but the argument
      has type 'unsigned long' [-Wformat]
    fprintf (outfile, "%5d %7d.%03d ", delay, timenow/1000, timenow%1000);
                           ~~~                ^~~~~~~~~~~~
                           %7lu
miditones_scroll.c:227:61: warning: format specifies type 'int' but the argument
      has type 'unsigned long' [-Wformat]
    fprintf (outfile, "%5d %7d.%03d ", delay, timenow/1000, timenow%1000);
                               ~~~~                         ^~~~~~~~~~~~
                               %03lu
miditones_scroll.c:233:36: warning: format specifies type 'unsigned int' but the
      argument has type 'long' [-Wformat]
    fprintf (outfile, "   %04X: ", lastbufptr-buffer); // offset
                          ~~~~     ^~~~~~~~~~~~~~~~~
                          %04lX

**Comment by LenShustek** [comment]
Thanks for the report.

Miditones: The fact that you got a clean compile is good news. But remember that this is a program with no graphical interface, so you need to run it from a command-line window. I think that's called "Terminal" in OS X, but you may need help from someone who knows the Mac. The last programming I did on an Apple was in the early 1980s on an Apple II.   :-)

Miditones_scroll: Your compiler environment differs from mine, so it doesn't have the strlcpy and strlcat safe string functions, and has different variable type sizes. I can fix those things, as I had done for Miditones several years ago.  I'll post new code in a day or two.

**Comment by LenShustek** [comment]
Ok, I posted a new version of Miditones_scroll. Let me know if that works for you.

(The comments hint at new Miditones code that supports volume and percussion, but I haven't released that  yet. I'm also experimenting with adding some instrument support, for a version of Playtune that uses a D-to-A converter to implement sample-based synthesis that sounds nicer than square waves.)

**Comment by Spaceddd** [comment]
Well, I haven't been able to figure out how to use the commands yet, it says that the miditones command is not found, however that's completely on my unknowledgeable end, so no problem. Everything compiles correctly now! Thank you very much, will check it :-)
